# Generated by Django 4.2.9 on 2024-12-19 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Registro de actividad', 'verbose_name_plural': 'Registros de actividad'},
        ),
        migrations.AddField(
            model_name='activitylog',
            name='content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='object_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
