# Generated by Django 4.2.9 on 2025-01-27 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mascotas', '0004_alter_mascota_fecha_registro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, help_text='Peso en kg', max_digits=5, null=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, help_text='Temperatura corporal', max_digits=4, null=True)),
                ('diagnostico_previo', models.TextField(blank=True, null=True)),
                ('tratamientos_anteriores', models.TextField(blank=True, null=True)),
                ('motivo_consulta', models.TextField()),
                ('sintomas', models.TextField()),
                ('diagnostico_actual', models.TextField()),
                ('tratamiento_recomendado', models.TextField()),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('SEGUIMIENTO', 'En Seguimiento')], default='ACTIVO', max_length=20)),
                ('proxima_consulta', models.DateField(blank=True, null=True)),
                ('medicamentos', models.TextField(blank=True, null=True)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas_medicas', to='mascotas.mascota')),
                ('veterinario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_medicas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ficha Médica',
                'verbose_name_plural': 'Fichas Médicas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
