# Generated by Django 4.2.9 on 2024-12-19 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especie',
            options={'verbose_name': 'especie', 'verbose_name_plural': 'especies'},
        ),
        migrations.AlterModelOptions(
            name='mascota',
            options={'ordering': ['-fecha_registro'], 'verbose_name': 'mascota', 'verbose_name_plural': 'mascotas'},
        ),
        migrations.AddField(
            model_name='mascota',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='especie',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='peso',
            field=models.DecimalField(decimal_places=2, help_text='Peso en kilogramos', max_digits=5),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas_propietario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='raza',
            field=models.CharField(max_length=100),
        ),
    ]
