# Generated by Django 4.2.9 on 2024-12-19 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0002_alter_especie_options_alter_mascota_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='especie',
            field=models.CharField(choices=[('PERRO', 'Perro'), ('GATO', 'Gato'), ('CONEJO', 'Conejo'), ('HAMSTER', 'Hámster'), ('AVE', 'Ave'), ('PEZ', 'Pez'), ('REPTIL', 'Reptil'), ('OTRO', 'Otro')], default='PERRO', max_length=20),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='raza',
            field=models.CharField(default='OTRO', max_length=50),
        ),
    ]
