# Generated by Django 4.2.9 on 2024-12-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0003_alter_mascota_especie_alter_mascota_raza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
