# Generated by Django 5.1.4 on 2024-12-17 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('motivo', models.TextField()),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('tratamiento', models.TextField(blank=True, null=True)),
                ('notas_adicionales', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=10)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['-fecha', '-hora'],
            },
        ),
        migrations.CreateModel(
            name='HistorialConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True)),
                ('diagnostico_anterior', models.TextField(blank=True, null=True)),
                ('tratamiento_anterior', models.TextField(blank=True, null=True)),
                ('notas_adicionales_anteriores', models.TextField(blank=True, null=True)),
                ('estado_anterior', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada')], max_length=10)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='consulta.consulta')),
            ],
            options={
                'verbose_name': 'Historial de Consulta',
                'verbose_name_plural': 'Historiales de Consultas',
                'ordering': ['-fecha_modificacion'],
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=50)),
                ('raza', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas_consulta', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FichaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alergias', models.TextField(blank=True)),
                ('condiciones_preexistentes', models.TextField(blank=True)),
                ('peso', models.FloatField()),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('mascota', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_medica', to='consulta.mascota')),
            ],
        ),
        migrations.AddField(
            model_name='consulta',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='consulta.mascota'),
        ),
        migrations.AddConstraint(
            model_name='consulta',
            constraint=models.UniqueConstraint(fields=('veterinario', 'fecha', 'hora'), name='unique_consulta'),
        ),
    ]
