# Generated by Django 4.2.9 on 2024-12-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0002_consulta_diagnostico_ia_consulta_peso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='tipo_servicio',
            field=models.CharField(choices=[('CONSULTA_GENERAL', 'Consulta General'), ('VACUNACION', 'Vacunación'), ('CIRUGIA', 'Cirugía'), ('EMERGENCIA', 'Emergencia'), ('CONTROL', 'Control')], default='CONSULTA_GENERAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
