# Generated by Django 4.2.9 on 2024-12-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0003_consulta_tipo_servicio_alter_consulta_costo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulta',
            options={'ordering': ['-fecha', '-creado_en'], 'verbose_name': 'Consulta', 'verbose_name_plural': 'Consultas'},
        ),
        migrations.RemoveConstraint(
            model_name='consulta',
            name='unique_consulta',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='hora',
        ),
        migrations.AlterField(
            model_name='consulta',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
