# Generated by Django 4.2.9 on 2024-12-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0004_alter_consulta_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='calificacion',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Muy Insatisfecho'), (2, '2 - Insatisfecho'), (3, '3 - Neutral'), (4, '4 - Satisfecho'), (5, '5 - Muy Satisfecho')], help_text='Calificación de la consulta por parte del cliente', null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='comentario',
            field=models.TextField(blank=True, help_text='Comentarios o feedback del cliente sobre la consulta', null=True),
        ),
    ]
