# Generated by Django 4.2.9 on 2024-12-19 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mascotas', '0003_alter_mascota_especie_alter_mascota_raza'),
        ('appointments', '0002_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-fecha', '-hora'], 'verbose_name': 'cita', 'verbose_name_plural': 'citas'},
        ),
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_appointment',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='creado_en',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='actualizado_en',
            new_name='ultima_modificacion',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='observaciones',
        ),
        migrations.AddField(
            model_name='appointment',
            name='notas',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada'), ('NO_ASISTIO', 'No Asistió')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='mascotas.mascota'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='motivo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='veterinario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_veterinario', to=settings.AUTH_USER_MODEL),
        ),
    ]
